language: ruby
rvm:
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
notifications:
  email: true
gemfile: Gemfile
